name: Java IEEE754 Converter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Check out the code
      uses: actions/checkout@v2

    - name: Build Java code
      run: |
        javac src/Main.java src/DeBlieux_Convertor.java

    - name: Run Java code
      run: java -cp src Main
