name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Compile DeBlieux_Convertor.java
      run: javac DeBlieux_Convertor.java
    - name: Run DeBlieux_Convertor
      run: java DeBlieux_Convertor
    - name: Compile GUI.java
      run: javac GUI.java
    - name: Run GUI
      run: java GUI
